name: build

on:
  push:
  pull_request:
  workflow_run:
    workflows:
      - scheduled
      - manual
    branches:
      - master
      - docking
    types:
      - requested

jobs:
  Windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Fix Projects
        shell: powershell
        run: |
          gci -recurse -filter "*.vcxproj" | ForEach-Object {
            (Get-Content $_.FullName) -Replace "<PlatformToolset>v\d{3}</PlatformToolset>", "<PlatformToolset>v143</PlatformToolset>" | Set-Content -Path $_.FullName
            (Get-Content $_.FullName) -Replace "<WindowsTargetPlatformVersion>[\d\.]+</WindowsTargetPlatformVersion>", "<WindowsTargetPlatformVersion>10.0.22621.0</WindowsTargetPlatformVersion>" | Set-Content -Path $_.FullName
          }

      - name: Build x64 example_glfw_opengl3
        run: MSBuild.exe examples/example_glfw_opengl3/example_glfw_opengl3.vcxproj /p:Platform=x64 /p:Configuration=Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-example_glfw_opengl3
          path: examples/example_glfw_opengl3/Release/example_glfw_opengl3.exe
